services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${KC_DB_HOST}
      KC_DB_URL_PORT: ${KC_DB_PORT}
      KC_DB_URL_DATABASE: ${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME_PROD}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: ${KC_PROXY}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      JAVA_OPTS_APPEND: ${JAVA_OPTS_APPEND}
    command:
      - start
      - --hostname-strict=false
      - --features=token-exchange
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 30s
      timeout: 10s
      retries: 10

  keycloak-init:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak_init
    restart: "no"
    env_file: .env
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      CLIENT_ALCALDIA_DUITAMA_SECRET: ${CLIENT_ALCALDIA_DUITAMA_SECRET}
      CLIENT_ALCALDIA_SOGAMOSO_SECRET: ${CLIENT_ALCALDIA_SOGAMOSO_SECRET}
      CLIENT_ALCALDIA_TUNJA_SECRET: ${CLIENT_ALCALDIA_TUNJA_SECRET}
      KC_SMTP_HOST: ${KC_SMTP_HOST}
      KC_SMTP_PORT: ${KC_SMTP_PORT}
      KC_SMTP_FROM: ${KC_SMTP_FROM}
      KC_SMTP_FROM_DISPLAY_NAME: ${KC_SMTP_FROM_DISPLAY_NAME}
      KC_SMTP_USER: ${KC_SMTP_USER}
      KC_SMTP_PASSWORD: ${KC_SMTP_PASSWORD}
    networks:
      - shared-network

networks:
  shared-network:
    external: true
