services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: dev-file
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: ${KC_PROXY}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      JAVA_OPTS_APPEND: ${JAVA_OPTS_APPEND}
    command:
      - start-dev
      - --hostname-strict=false
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 30s
      timeout: 10s
      retries: 10

  keycloak-init:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak_init
    restart: "no"
    env_file: .env
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      CLIENT_ALCALDIA_DUITAMA_SECRET: ${CLIENT_ALCALDIA_DUITAMA_SECRET}
      CLIENT_ALCALDIA_SOGAMOSO_SECRET: ${CLIENT_ALCALDIA_SOGAMOSO_SECRET}
      CLIENT_ALCALDIA_TUNJA_SECRET: ${CLIENT_ALCALDIA_TUNJA_SECRET}
    networks:
      - shared-network

networks:
  shared-network:
    external: true
